name: "Build"

on:
  pull_request:

permissions: read-all

jobs:
  Build:
    name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: '1.21.0'
    - name: Install libpcap-dev
      run: sudo apt-get install -y libpcap-dev
    - run: go build -o scheduler cmd/scheduler/main.go
    - run: go build -o worker cmd/worker/main.go
    - run: go build -o analyze cmd/analyze/main.go
    - run: go build -o loader load.go
      working-directory: function/loader
    - run: go build -o staticanalyze staticanalyze.go
      working-directory: sandboxes/staticanalysis
