name: "Build docker"

on:
  pull_request:

  push:
    paths-ignore:
      - '**.md'

permissions: read-all

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    - name: setup-go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: '1.21.0'

    - name: Enable docker experimental
      run: |
        echo $'{"experimental": true}' | sudo dd status=none of=/etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: build_docker
      run: make build_prod_images
